version: '3'

services:
  db:
    image: mysql:5.7 # プロダクトで使うならバージョンはlatestじゃないほうが良いです
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root # MySQLパスワード設定
      MYSQL_DATABASE: test # MySQLデータベース名設定
      TZ: 'Asia/Tokyo'
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mysql_web
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
