version: "3"

services:
  mysql:
    image: mysql:5.7 # プロダクトで使うならバージョンはlatestじゃないほうが良いです
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root # MySQLパスワード設定
      MYSQL_DATABASE: test # MySQLデータベース名設定
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"