service: serverless-example

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-1
  environment:
    NODE_ENV: development
    STAGE: local
    DB_HOST: localhost
    DB_PORT: 3306
    DB_USERNAME: root
    DB_PASSWORD: root
    DB_DATABASE: test

functions:
  main:
    handler: dist/index.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
